In [1]:
import numpy as np
import pandas as pd

In [36]:
x = np.arange(100)
x[-17: -5]

array([83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94])

In [25]:
x.sum(axis=1)

array([ 55, 155, 255, 355, 455, 555, 655, 755, 855, 955])

In [41]:
np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [26]:
class A:
    
    def __init__(self, value):
        self.val = value

    def __add__(self, o):
        return self.val + o.val
    
    def __sub__(self, o):
        return self.val - o.val
    
    def __mul__(self, o):
        return self.val * o.val
    
    def __mod__(self,o):
        return self.val % o.val
    
    def __floordiv__(self, o):
        return self.val // o.val
    
    def __truediv__(self, o):
        return self.val / o.val
    
    def __divmod__(self, o):
        return divmod(self.val, o.val)
    
    def __pow__(self, o):
        return pow(self.val, o.val)
    
x = A(5)
y = A(4)

print("Add\t\t",x+y)
print("Div\t\t",x/y)
print("Mod\t\t",x%y)
print("Mul\t\t",x*y)
print("Diff\t\t",x-y)
print("FloorDiv\t", x//y)
print("DivMod\t\t", divmod(x,y))
print("Power\t\t", pow(x,y))

Add		 9
Div		 1.25
Mod		 1
Mul		 20
Diff		 1
FloorDiv	 1
DivMod		 (1, 1)
Power		 625


In [2]:
((500//7)%5)**3

1

In [18]:
print('i love python'[-11:-7])

love 


In [21]:
l = [1,2,3]
print(l*2)

[1, 2, 3, 1, 2, 3]


In [23]:
k = [[1,2,3], [4,5,6], [7,8,9,10]]
k[2:]

[[7, 8, 9, 10]]

In [24]:
T = (3,5,7,11)
T.append(9)

AttributeError: 'tuple' object has no attribute 'append'

In [25]:
d = {1:'2', 2:'3'}
for i in d:
    print(i)

1
2


In [31]:
def fn(*args):
    return(sum(args))

print(fn(1,2,3,4,5))
print(fn(6,7,8))

15
21


In [33]:
print([i**2 for i in [1,2,3,4]])

[1, 4, 9, 16]


In [40]:
L = [1,2,3,4]
list(map(lambda x : x**2, L))

[1, 4, 9, 16]

In [46]:
list_1 = [1,2,3]
list_2 = [3,4,5]
list_3 = [7,8,9]
arr = np.array([list_1, list_2, list_3])

In [47]:
arr

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

In [60]:
for x in range(4):
    i,j = [2,3,4,5][x],[7,8,9,6][x]
    print(i*j, end=' ')

14 24 36 30 

In [66]:
np.array([5*x for x in range(1,11)])

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [65]:
np.arange(5,51,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [74]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([[9,8,7], [6,5,4], [3,2,1]])
print("Dot::\n", np.dot(a,b))
print("Cross::\n", np.cross(a,b))

Dot::
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Cross::
 [[-10  20 -10]
 [-10  20 -10]
 [-10  20 -10]]


In [75]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.linalg.det(a)

6.66133814775094e-16